# Generated by Django 4.0.6 on 2022-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0002_coding'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.TextField(blank=True, db_column='geneID', null=True)),
                ('transcriptid', models.TextField(blank=True, db_column='transcriptID', null=True)),
                ('numbers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Gene_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebToolCoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invented', models.IntegerField()),
                ('popularity', models.FloatField()),
            ],
            options={
                'db_table': 'web_tool_coding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebToolGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=100)),
                ('transcript_id', models.CharField(max_length=100)),
                ('numbers', models.IntegerField()),
            ],
            options={
                'db_table': 'web_tool_gene',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Coding',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
    ]
