# Generated by Django 4.0.6 on 2022-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0006_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneTbl2',
            fields=[
                ('numid', models.IntegerField(blank=True, db_column='Num_ID', null=True)),
                ('geneid', models.TextField(blank=True, db_column='Gene_ID', primary_key=True, serialize=False)),
                ('transcriptid', models.TextField(blank=True, db_column='transcript_ID', null=True)),
                ('numbers', models.IntegerField(blank=True, db_column='#oftranscripts', null=True)),
            ],
            options={
                'db_table': 'Gene_TBL2',
                'managed': False,
            },
        ),
    ]
