# Generated by Django 4.0.6 on 2022-09-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0007_genetbl2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrnaTbl',
            fields=[
                ('numid', models.IntegerField(blank=True, db_column='Num_ID', null=True)),
                ('geneid', models.TextField(blank=True, db_column='Gene_ID', primary_key=True, serialize=False)),
                ('transcriptid', models.TextField(blank=True, db_column='mRNAIsoforms', null=True)),
                ('numbers', models.IntegerField(blank=True, db_column='Numbers', null=True)),
            ],
            options={
                'db_table': 'mRNA_TBL',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GeneTbl',
        ),
        migrations.DeleteModel(
            name='GeneTbl2',
        ),
    ]
