# Generated by Django 4.0.6 on 2022-09-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0009_ncrnatbl_dicty_keyval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.DeleteModel(
            name='NcrnaTbl',
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
