# Generated by Django 4.0.6 on 2022-08-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_tool', '0003_genetbl_webtoolcoding_webtoolgene_delete_coding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneTbl',
        ),
        migrations.DeleteModel(
            name='WebToolCoding',
        ),
        migrations.DeleteModel(
            name='WebToolGene',
        ),
    ]
