# Generated by Django 4.0.6 on 2022-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_tool', '0004_delete_genetbl_delete_webtoolcoding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.TextField(blank=True, db_column='geneID', null=True)),
                ('transcriptid', models.TextField(blank=True, db_column='transcriptID', null=True)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('numid', models.IntegerField(blank=True, db_column='numID', null=True)),
            ],
            options={
                'db_table': 'Gene_TBL',
                'managed': False,
            },
        ),
    ]
